# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_image', models.ImageField(default='images/ipad.jpg', upload_to='images/')),
                ('price', models.IntegerField()),
                ('item_description', models.CharField(max_length=50)),
                ('item_stock', models.IntegerField()),
            ],
        ),
    ]
